---
- name: Clean up any downloaded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ download_dir }}/node_exporter-{{ version }}.{{ system_type }}.tar.gz"
    - "{{ download_dir }}/node_exporter-{{ version }}.{{ system_type }}"
