---
# Variable setup
- name: Load system specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_system }}_{{ ansible_architecture }}.yml"
        - defaults.yml
      paths:
        - 'vars'

# Run tasks
# Download & Install node_exporter
- import_tasks: install.yml

# Set node_exporter configuration
- import_tasks: configure.yml

# Setup node_exporter as a service
- import_tasks: create_service.yml

# Clean up the mess
- import_tasks: cleanup.yml
